language: python

git:
  submodules: false

os:
  - linux

python:
  - 3.6
  - 3.7

install:
  - sudo apt-get update
  - pip install tensorflow==1.4
  - pip install pytest
  - pip install codecov
  - python setup.py install

script:
  - python setup.py test
  - codecov
